### ISSUE TITLE
Import DPU authentication problem - dependent on backend on/off

### ISSUE THREAD

**Issue by skodapetr** [mff-uk/odcs#379]
DPU Create .. when I click on save I get:

![image](https://f.cloud.github.com/assets/3341693/1088437/c1f24060-1632-11e3-9854-4262616f4822.png)

Please keep me inform about the progress as there are few issues #249 and #247 that fully depend on this functionality.

**Comment by skodapetr** [comment]
Same exception also appear if I as a "user" try to open DPU template detail from tree. 

As admin I do not see any DPU in DPU Templates is that expected behaviour?

**Comment by kukharm** [comment]
Same exception: Scheduler/add new scheduling rule; Settings after clicking any of tab or button save

**Comment by janvojt** [comment]
This should be resolved in 6b5b92a5, if not please reopen.

**Comment by jakubklimek** [comment]
Another exception, but still does not work. This is when clicking save. ![image](https://f.cloud.github.com/assets/718827/1096576/e3b3788e-1701-11e3-9f9d-adbfe1e5ac50.png)

**Comment by jakubklimek** [comment]
Interesting, Access is denied is shown when backend is not running. The first one is shown when it is. I thought the frontend should be independent here.
