### ISSUE TITLE
Sometimes when I click Show log in Exec. Monitor nothing happens

### ISSUE THREAD

**Issue by jakubklimek** [mff-uk/odcs#477]
Sometimes when I click Show log in Exec. Monitor, the "waiting symbol" appears, then disappears and nothing happens.

Then I click it again, the waiting symbol appears, does not disappear, and the log is still not shown.

**Comment by bogo777** [comment]
This was related to refreshing and has been improved by improving refreshing. But it can still occur, when object on which the actions is called is currently being refreshed.

**Comment by tomas-knap** [comment]
Bohuslav, is this still occurying? Do you know the proper solution for that?

**Comment by tomas-knap** [comment]
related to #462

**Comment by tomas-knap** [comment]
Bohuslav, is this still relevant? Or was it solved with Eclipse ORM framework?

**Comment by bogo777** [comment]
It depends on refresh time, so Eclipse ORM framework helped, but it can still occur.

**Comment by tomas-knap** [comment]
Does Vaadin provide some solution, because this seems to be quite a common problem?

**Comment by tomas-knap** [comment]
Relates to #625

**Comment by tomas-knap** [comment]
When done check that this issue is solved

**Comment by tomas-knap** [comment]
Should be solved when #625 is solved
